### PR TITLE
zv: Add missing From implementations for Value::Str

### LINKED ISSUE #1234: Zvariant: Value should implement From<Arc<str>>
# Description
The Value struct in zvariant does not implement `From<Arc<str>>` even though the Str helper struct does.
This means you can no longer call `.into()` to convert your Arc into a Value like you can with &str or String.
More importantly though you now need to manually map the values  of Vecs or HashMaps that use `Arc<str>` to construct the Array or Dict variant.

# Example
```rust
use std::sync::Arc;
use zvariant::Value;

fn main() {
    let arced: Arc<str> = "Arc'ed &str".into();

    let v1: Value = "Value".into(); // This works because Value implements From<&str>
    let v2: Value = arced.into(); // This does not, even though Str implements From<Arc<str>>
    let v3 = Value::Str(arced.into()); // We can manually turn our Arc into the helper Str struct
    
    // But for Arrays or Dicts this does not work:
    let vec: Vec<Arc<str>> = ["Hello", "World", "!"].iter().map(|v| (*v).into()).collect();

    // This does not work because Array only implements From<Vec<T>> where T implements Into<Value<'a>>
    let v4 = Value::Array(vec.into());

    // Like above we need to manually convert the Arcs for this to work
    let mapped: Vec<Value> = vec
        .iter()
        .map(|v| Value::Str(Arc::clone(v).into()))
        .collect();
    let v5 = Value::Array(mapped.into());

}
```

# Compiler output
```
error[E0277]: the trait bound `zvariant::Structure<'_>: From<Arc<str>>` is not satisfied
 --> src/main.rs:9:27
  |
9 |     let v2: Value = arced.into(); // This does not, even though Str implements From<Arc<str>>
  |                           ^^^^ the trait `From<Arc<str>>` is not implemented for `zvariant::Structure<'_>`
  |
  = help: the following other types implement trait `From<T>`:
            `zvariant::Structure<'_>` implements `From<(T0, T1)>`
            `zvariant::Structure<'_>` implements `From<(T0, T1, T2)>`
            `zvariant::Structure<'_>` implements `From<(T0, T1, T2, T3)>`
            `zvariant::Structure<'_>` implements `From<(T0, T1, T2, T3, T4)>`
            `zvariant::Structure<'_>` implements `From<(T0, T1, T2, T3, T4, T5)>`
            `zvariant::Structure<'_>` implements `From<(T0, T1, T2, T3, T4, T5, T6)>`
            `zvariant::Structure<'_>` implements `From<(T0, T1, T2, T3, T4, T5, T6, T7)>`
            `zvariant::Structure<'_>` implements `From<(T0, T1, T2, T3, T4, T5, T6, T7, T8)>`
          and 8 others
  = note: required for `Arc<str>` to implement `Into<zvariant::Structure<'_>>`
  = note: required for `zvariant::Value<'_>` to implement `From<Arc<str>>`
  = note: 1 redundant requirement hidden
  = note: required for `Arc<str>` to implement `Into<zvariant::Value<'_>>`

error[E0277]: the trait bound `zvariant::Structure<'_>: From<Arc<str>>` is not satisfied
  --> src/main.rs:16:31
   |
16 |     let v4 = Value::Array(vec.into());
   |                               ^^^^ the trait `From<Arc<str>>` is not implemented for `zvariant::Structure<'_>`
   |
   = help: the following other types implement trait `From<T>`:
             `zvariant::Structure<'_>` implements `From<(T0, T1)>`
             `zvariant::Structure<'_>` implements `From<(T0, T1, T2)>`
             `zvariant::Structure<'_>` implements `From<(T0, T1, T2, T3)>`
             `zvariant::Structure<'_>` implements `From<(T0, T1, T2, T3, T4)>`
             `zvariant::Structure<'_>` implements `From<(T0, T1, T2, T3, T4, T5)>`
             `zvariant::Structure<'_>` implements `From<(T0, T1, T2, T3, T4, T5, T6)>`
             `zvariant::Structure<'_>` implements `From<(T0, T1, T2, T3, T4, T5, T6, T7)>`
             `zvariant::Structure<'_>` implements `From<(T0, T1, T2, T3, T4, T5, T6, T7, T8)>`
           and 8 others
   = note: required for `Arc<str>` to implement `Into<zvariant::Structure<'_>>`
   = note: required for `zvariant::Value<'_>` to implement `From<Arc<str>>`
   = note: 3 redundant requirements hidden
   = note: required for `Vec<Arc<str>>` to implement `Into<zvariant::Array<'_>>`
```

# Version details
rustc: 1.84.1 (e71f9a9a9 2025-01-27)
zvariant: 5.2.0
edition: 2021

### PR DESCRIPTION
**Pull request by jasger9000**
This PR mainly fixes Value not implementing From for Arced or Cowed strs.
Additionally I replaced the manual implementations of `From<String>` and `From<&'v String>` with the macro one.
I think this makes the PR not atomic anymore, sorry about that. 😅

fixes #1234

### CODE REVIEW

**Review by zeenix — APPROVED** [review]
Thanks so much! I don't understand how it's "non-atomic". You nicely split each logical change into separate commits and that's exactly what atomic commits is all about.

File: zvariant/src/into_value.rs [hunk 1]
```diff
@@ -49,6 +49,9 @@ into_value_from_both!(i64, I64);
 into_value_from_both!(f32, F64);
 into_value_from_both!(f64, F64);
 
+into_value!(Arc<str>, Str);
+into_value!(Cow<'a, str>, Str);
```
Comment (zeenix) [inline zvariant/src/into_value.rs:53]: just for future ref, this is not bug fix but rather a new feature (despite its importance) so ✨ would have been a better emoji. :)

Comment (jasger9000) [reply zvariant/src/into_value.rs:53]: Noted, thanks :)

**Comment by jasger9000** [comment]
> I don't understand how it's "non-atomic". You nicely split each logical change into separate commits and that's exactly what atomic commits is all about.

I was referring to the PR as a whole, since I was committing something that didn't have much to do with what the PR was trying to address.

**Comment by zeenix** [comment]
> > I don't understand how it's "non-atomic". You nicely split each logical change into separate commits and that's exactly what atomic commits is all about.
> 
> I was referring to the PR as a whole, since I was committing something that didn't have much to do with what the PR was trying to address.

Ah ok. While smaller PRs are usually better, I don't think it's important to keep PRs completely atomic. In fact splitting PRs too much can cause a lot of noise in the git history for very little gain. Atomic commits OTOH have real benefits (every change is documented, easy to bisect when hunting a regression down, easy to revert changes etc). Hence why I only stress on atomic commits.
