### PR TITLE
✨ zb: allows specifying uid in connection

### LINKED ISSUE #1003: Customisable sasl_auth_id
I work on IIoT devices and I am rewriting a codebase (doing a PoC actually) from C# + Tmds.DBus to Rust with rusty-network-manager + zbus.

I need to connect using a specific user id (0), which I can configure with Tmds.DBus, but not with zbus and this makes handshake attempts fail ("Handshake (Exhausted available AUTH methods)").

As a workaround I cloned your repository and hardcoded the 0 and it works, but it would be nice to be able to specify it in the builder.

### PR DESCRIPTION
**Pull request by lincemiope**
Linked issue [#1003](https://github.com/z-galaxy/zbus/issues/1003).

This is how I implemented it in my fork

I ran the tests and I got errors although I have no idea what might have caused them, I am not on a linux machine so it might be it.

Fixes #1003.

### CODE REVIEW

**Comment by zeenix** [comment]
> This is how I implemented it in my fork

Thank you. I'll take a look soon but please review and follow [our contribution guideline](https://github.com/z-galaxy/zbus/blob/main/CONTRIBUTING.md#submitting-bug-reports-and-feature-requests) to the best of your abilities. :pray: 

> I ran the tests and I got errors although I have no idea what might have caused them, I am not on a linux machine so it might be it.

What kind of errors and what OS did you get these errors? I'll run the CI anyway, which tests of Linux and Windows and checks if code compiles on various others (e.g Mac).

File: zbus/src/connection/builder.rs [hunk 1]
```diff
@@ -203,6 +204,13 @@ impl<'a> Builder<'a> {
         self
     }
 
+    /// Lets you impersonate a user
```
Comment (zeenix) [inline zbus/src/connection/builder.rs]: We'll need a bit more docs than this. Also missing `.`. :)

File: zbus/src/connection/mod.rs [hunk 2]
```diff
@@ -38,7 +38,7 @@ pub use socket::Socket;
 mod socket_reader;
 use socket_reader::SocketReader;
 
-pub(crate) mod handshake;
+pub mod handshake;
```
Comment (zeenix) [inline zbus/src/connection/mod.rs]: unneeded and undesirable change.

File: zbus/src/connection/builder.rs [hunk 3]
```diff
@@ -203,6 +204,13 @@ impl<'a> Builder<'a> {
...
+    pub fn impersonate_user_id(mut self, id: usize) -> Self {
```
Comment (zeenix) [inline zbus/src/connection/builder.rs]: * This is unix-specific and I think it needs to be `#[cfg(unix)]`.
* I think `user_id` is good enough. It's not always going to be used for impersonating. The struct field will also need update.
* `blocking::connection::Builder` will need a wrapper for this too.

**Comment by lincemiope** [comment]
> > This is how I implemented it in my fork
> 
> Thank you. I'll take a look soon but please review and follow [our contribution guideline](https://github.com/z-galaxy/zbus/blob/main/CONTRIBUTING.md#submitting-bug-reports-and-feature-requests) to the best of your abilities. 🙏
> 
> > I ran the tests and I got errors although I have no idea what might have caused them, I am not on a linux machine so it might be it.
> 
> What kind of errors and what OS did you get these errors? I'll run the CI anyway, which tests of Linux and Windows and checks if code compiles on various others (e.g Mac).

I don't remember, probably a mac. I reran them today on Ubuntu 24.04 and they were all good

**Comment by lincemiope** [comment]
Do I need to do more?

**Comment by zeenix** [comment]
> Do I need to do more?

Sorry, I've been super busy at work so didn't get a chance to look yet but it seems you're not fully following our contribution guidelines around comit messages. Please squash your fixup commits into the first commit, follow the commit log convention, add emoji prefix to the commit and then force push. 🙏

File: zbus/src/connection/builder.rs (hunk 1 above)
Comment (zeenix) [reply zbus/src/connection/builder.rs]: This is not quite resolved yet. We need to describe the use case(s) here. Also I'd not use the term "impersonate" in the docs either.

**Comment by zeenix** [comment]
> Please squash your fixup commits into the first commit, follow the commit log convention, add emoji prefix to the commit and then force push. 🙏

Actually, nevermind about this part. I'll just squash merge all the commits at the end. Just look into the rest.

**Comment by lincemiope** [comment]
I added a test but it fails with the message: "Unknown command: \0AUTH EXTERNAL 31303030\r\n".

I am sorry, but I have never created a dbus server, I use it only as a client and the "external experience" is dev environment only, in production we use session.

**Comment by zeenix** [comment]
> I am sorry, but I have never created a dbus server, I use it only as a client and the "external experience" is dev environment only, in production we use session.

I'm not sure I follow. All buses use "EXTERNAL" auth and if they don't, you have a major security issue at your hand (since we don't support "COOKIE" auth anymore so the only option left is "ANONYMOUS", which should **never** be used in prod.

**Comment by lincemiope** [comment]
> > I am sorry, but I have never created a dbus server, I use it only as a client and the "external experience" is dev environment only, in production we use session.
> 
> I'm not sure I follow. All buses use "EXTERNAL" auth and if they don't, you have a major security issue at your hand (since we don't support "COOKIE" auth anymore so the only option left is "ANONYMOUS", which should **never** be used in prod.

I know we don't use anonymous or cookie, then I guess we use external. But still my experience is as a client.

File: zbus/tests/issue/issue_1003.rs [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+#[test]
+#[timeout(15000)]
+#[instrument]
+fn issue_1003() {
+    // Connect to a server using [`AuthMechanism::External`] and providing a user id
+    block_on(async move {
+        let (p0, p1) = {
+            #[cfg(not(feature = "tokio"))]
+            {
+                let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
```
Comment (zeenix) [inline zbus/tests/issue/issue_1003.rs]: I don't think we can do external auth on TCP on unix (yet). You want to use a pipe here. See the p2p tests in zbus/src/connection/mod.rs for inspiration.

File: zbus/tests/issue/issue_1003.rs [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+                let addr = listener.local_addr().unwrap();
+                let p1 = tokio::net::TcpStream::connect(addr).await.unwrap();
+                let p0 = listener.accept().await.unwrap().0;
+
+                (p0, p1)
+            }
+        };
+
+        let (service_conn_builder, client_conn_builder) = (
+            Builder::tcp_stream(p0).auth_mechanism(AuthMechanism::External),
```
Comment (zeenix) [inline zbus/tests/issue/issue_1003.rs]: You're not specifying the UID to the server so the server will expect the actual UID.

**Comment by zeenix** [comment]
> But still my experience is as a client.

I understand but the PR isn't useful unless you cover both sides. If you don't feel like covering the server side as well, just let me know and I'll see if I can finish the PR when I've the time. @alyssais Perhaps you'd be interested in helping get this to the finish line?

**Comment by lincemiope** [comment]
> > But still my experience is as a client.
> 
> I understand but the PR isn't useful unless you cover both sides. If you don't feel like covering the server side as well, just let me know and I'll see if I can finish the PR when I've the time. @alyssais Perhaps you'd be interested in helping get this to the finish line?

Please do

**Comment by alyssais** [comment]
> @alyssais Perhaps you'd be interested in helping get this to the finish line?

I am but won't have time before December.

**Comment by zeenix** [comment]
> > @alyssais Perhaps you'd be interested in helping get this to the finish line?
> 
> I am

Cool, thanks.

> but won't have time before December.

There's no hurry. 😊

**Comment by zeenix** [comment]
@alyssais any luck?

I hate unfinished PRs. If you can't finish this, I'm going to close this.

**Comment by lincemiope** [comment]
> @alyssais any luck?
> 
> I hate unfinished PRs. If you can't finish this, I'm going to close this.

I could finish it if I knew how to fix the test

**Comment by zeenix** [comment]
> I could finish it if I knew how to fix the test

As [we concluded already](https://github.com/z-galaxy/zbus/pull/1574#issuecomment-3557804666), it likely just needs to do the same for the server side code/API. You can give it a try and I'd be happy to help you if you get stuck on something or can't understand something.

**Comment by lincemiope** [comment]
> > I could finish it if I knew how to fix the test
> 
> As [we concluded already](https://github.com/z-galaxy/zbus/pull/1574#issuecomment-3557804666), it likely just needs to do the same for the server side code/API. You can give it a try and I'd be happy to help you if you get stuck on something or can't understand something.

I retook it, tried to do like in the p2p test

```rust
#[cfg(feature = "p2p")]
#[test]
#[timeout(15000)]
#[instrument]
fn issue_1003() {
    #[cfg(not(feature = "tokio"))]
    use std::os::unix::net::UnixStream;
    #[cfg(feature = "tokio")]
    use tokio::net::UnixStream;
    #[cfg(all(windows, not(feature = "tokio")))]
    use uds_windows::UnixStream;

    let guid = zbus::Guid::generate();

    let (p0, p1) = UnixStream::pair().unwrap();

    block_on(async move {
        futures_util::try_join!(
            Builder::unix_stream(p1).auth_mechanism(AuthMechanism::External).user_id(UID).p2p().build(),
            Builder::unix_stream(p0).auth_mechanism(AuthMechanism::External).user_id(UID).server(guid).unwrap().p2p().build(),
        )
    }).unwrap();
}
```

and got this odd error:

> EXTERNAL rejected by the server. Accepted mechanisms: [EXTERNAL]

**Comment by zeenix** [comment]
> and got this odd error:
> 
> > EXTERNAL rejected by the server. Accepted mechanisms: [EXTERNAL]

Of course! You did not modify the server-side so it has no idea that you're trying to cheat. :) This is no new information. The log of the failing test case, is giving you even more info (which you can also get locally if you enable tracing with `RUST_LOG=zbus=trace`).

**Comment by lincemiope** [comment]
> > and got this odd error:
> > > EXTERNAL rejected by the server. Accepted mechanisms: [EXTERNAL]
> 
> Of course! You did not modify the server-side so it has no idea that you're trying to cheat. :) This is no new information. The log of the failing test case, is giving you even more info (which you can also get locally if you enable tracing with `RUST_LOG=zbus=trace`).

The situation must look farcical to you, but I have no idea what is expected of me to do. I enabled the trace and I can see the exchanges, but I have no clue how to fix the issue.

**Comment by zeenix** [comment]
> but I have no clue how to fix the issue.

You modified the client-side of the handshake, look at the server side too? If you can't figure it out, ask specific questions and I will try my best to help out as much as I can. I'm sorry if that wasn't clear when I asked before.

**Comment by zeenix** [comment]
> You did not modify the server-side so it has no idea that you're trying to cheat. :)

Just like the client-side use the actual user name by default, the server side does exactly the same (in fact they share the code to retrieve that IIRC) and it rejects the handshake because it sees the wrong user ID. I hope that's a good hint to get you started?

File: zbus/tests/issue/issue_1003.rs (hunk 4 above)
Comment (zeenix) [reply zbus/tests/issue/issue_1003.rs]: @lincemiope I think I've fixed the server side. If I did, it was a one-liner in the end. However, the test still fails because you didn't even address the comments that had nothing to do with server-side code.  :(

**Comment by zeenix** [comment]
I believe I fixed the issue. As I suspected, it was just a one liner, other than some mistakes in the PR, which I had already pointed out to @lincemiope in specific.

Anyway, I took the liberty of pushing the fixes directly into the PR and rebased on the latest main. Hopefully the CI is now green and we can merge this now.

**Comment by lincemiope** [comment]
> I believe I fixed the issue. As I suspected, it was just a one liner, other than some mistakes in the PR, which I had already pointed out to @lincemiope in specific.
> 
> Anyway, I took the liberty of pushing the fixes directly into the PR and rebased on the latest main. Hopefully the CI is now green and we can merge this now.

I cannot see what changed

**Comment by zeenix** [comment]
> I cannot see what changed

Locally, you can do `git diff e56af7ab` (after updating your local branch, e.g using `git pull --rebase`).

**Comment by zeenix** [comment]
> > I cannot see what changed
> 
> Locally, you can do `git diff e56af7ab` (after updating your local branch, e.g using `git pull --rebase`).

Unfortunately that will also show you unrelated changes from main branch, due to the rebase (which was necessary for getting the fixes against the latest rust release).
