### PR TITLE
🐛 macro: ignore r# prefix in method names

### LINKED ISSUE #214: proxy macro panics when one of the methods is `fn r#type(&self)`
In GitLab by @MaxVerevkin on Oct 13, 2021, 17:43

```rust
#[dbus_proxy(
    interface = "org.freedesktop.UPower.Device",
    default_service = "org.freedesktop.UPower"
)]
trait Device {
    /// Type property
    #[dbus_proxy(property)]
    fn r#type(&self) -> zbus::Result<u32>;
}
```
Fails:
```
error: custom attribute panicked
  --> src/blocks/battery/zbus_upower.rs:24:1
   |
24 | / #[dbus_proxy(
25 | |     interface = "org.freedesktop.UPower.Device",
26 | |     default_service = "org.freedesktop.UPower"
27 | | )]
   | |__^
   |
   = help: message: `"cached_r#type"` is not a valid identifier
```

### PR DESCRIPTION
**Pull request by hepptho**
The `r#` prefix required for identifiers that would otherwise be rust keywords is no longer carried over into the dbus method / property names when used in interface methods.

Users no longer have to resort to the `name` attribute in these cases.

There is a related open issue regarding `r#` in parameter names (#158).
That is not addressed here, but might be in a follow-up PR.

<del>This is technically a BREAKING CHANGE,
though it seems unlikely anyone wants an `r#` prefix in their dbus names or relies upon the previous behavior.</del>

Closes #214

### CODE REVIEW

**Comment by hepptho** [comment]
Disclaimer: I am not a macro expert at all. I hope this change is small enough not to hide any stupid mistakes, but if it does, I apologize.

File: zbus_macros/src/iface.rs [hunk 1]
```diff
@@ -257,6 +257,9 @@ impl MethodInfo {
                 assert!(name.starts_with("set_"));
                 name = name[4..].to_string();
             }
+            if name.starts_with("r#") {
```
Comment (zeenix) [inline zbus_macros/src/iface.rs]: nit: This should be an `else if` I think, since this won't happen for the property setters that the previous `if` is for?

File: zbus_macros/src/proxy.rs [hunk 2]
```diff
@@ -542,7 +547,19 @@ fn gen_proxy_method_call(
...
+            ident
+        }
+        Err(_) => {
+            // Ident::new("r#keyword, ...) panics, even though it's a valid identifier.
+            // syn::parse_str works, so we use that instead.
+            let mut ident = parse_str::<Ident>(format!("r#{snake_case_name}").as_str())?;
+            ident.set_span(Span::call_site());
+            ident
+        }
+    };
```
Comment (zeenix) [inline zbus_macros/src/proxy.rs]: I'm puzzled. Isn't the `snake_case` name passed to this method already has the `r#` removed at line 212?

**Review by zeenix — CHANGES_REQUESTED** [review]
Thanks so much for looking into this. Apart from the nit and a question, could we also add a small test case for this? Just add a method using `r#` in the e2e testcase (file `zbus/tests/iface_and_proxy/iface.rs`).

File: zbus_macros/src/iface.rs (hunk 1 above)
Comment (hepptho) [reply zbus_macros/src/iface.rs]: Yes, they're exclusive. I've fixed it.

File: zbus_macros/src/proxy.rs (hunk 2 above)
Comment (hepptho) [reply zbus_macros/src/proxy.rs]: Yes, the `r#` was removed. That is good when the string is later used as part of another identifier (like `cached_{name}`, which caused the error in #214), because `r#` is not valid in the middle.
And mostly it is used like that, but here it is used as-is, meaning for it to be valid, we need to add the `r#`  back if it's a keyword, and that is what happens.
If `snake_case_name` is not a valid identifier, the first `parse_str` will return an Err and in that case we  try again with the `r#` prefix.

I've added a comment that hopefully makes it clearer.

**Comment by hepptho** [comment]
Changes in the last force-push:

- used `if else` according to comment above
- added clippy fixes
- added comment
- added tests (which was pleasant to do, that test setup is quite nice :+1: )

**Comment by zeenix** [comment]
Thanks so much. I'll have a look soon.

> added clippy fixes

If the fixes were to code you didn't touch, please split them into a separate commit as per our practice of atomic commits. 🙏

**Comment by hepptho** [comment]
Some clippy fixes were in lines I didn't touch, but necessary as a direct consequence of my changes: `method_name` in `proxy.rs` is now `&str` instead of `String`, and clippy complained about now unnecessary `&` when passed as a parameter down the line ("reference immediately dereferenced by the compiler").
Should they still be separated out?

**Comment by zeenix** [comment]
> Some clippy fixes were in lines I didn't touch, but necessary as a direct consequence of my changes: `method_name` in `proxy.rs` is now `&str` instead of `String`, and clippy complained about now unnecessary `&` when passed as a parameter down the line ("reference immediately dereferenced by the compiler").
> Should they still be separated out?

Ah ok. No, that's why started with "if". I just hadn't had a chance to look more closely to the changes.

File: zbus_macros/src/proxy.rs (hunk 2 above)
Comment (zeenix) [reply zbus_macros/src/proxy.rs]: Thanks for explaining. That makes sense now.

However,  instead of recreating the identifier with `r#`, why don't we just pass the original to this method as well? Then we don't need this complication.

Comment (hepptho) [reply zbus_macros/src/proxy.rs]: That's an option, I just hesitated because there's already a lot of parameters and I wasn't sure how to name them.
But you're right, it's not great as it is either.
What do you think of a helper struct to keep them together, like this:

```rust
struct MethodName {
    original: String,
    r#_stripped: String,
}
```

Comment (hepptho) [reply zbus_macros/src/proxy.rs]: Or maybe `RustMethodName`, to avoid confusion with dbus methods.

Comment (zeenix) [reply zbus_macros/src/proxy.rs]: > What do you think of a helper struct to keep them together, like this:
> Or maybe `RustMethodName`, to avoid confusion with dbus methods.

Sounds good to me. We could actually just make a `Method` struct, add all params into it and then make this function a method of that, called just as `generate`. However, let's not mix this refactor into this change. I'd suggest you first add a new parameter to this function and then do the refactor on top in separate commit.

Comment (hepptho) [reply zbus_macros/src/proxy.rs]: Done. Turns out we don't need both variants in `gen_proxy_method_call`, only the one with `r#`.
The struct isn't necessary, I think.
I would still like to rename parameters in `gen_proxy_property`, `gen_proxy_signal`, and `gen_proxy_method_call` to be clear as to what they get. The latter in particular is confusing, because the parameter names are not consistent with the names of the variables passed to it (`member_name` / `method_name` are switched) .
New commit, or squash into the same one?

**Comment by hepptho** [comment]
Change in the last force-push:

Pass the original rust method name to `gen_proxy_method_call`, to avoid having to add back the `r#` prefix in case of keyword.

File: zbus_macros/src/proxy.rs (hunk 2 above)
Comment (zeenix) [reply zbus_macros/src/proxy.rs]: > Done. Turns out we don't need both variants in `gen_proxy_method_call`, only the one with `r#`.
> The struct isn't necessary, I think.

Sure.

> I would still like to rename parameters in `gen_proxy_property`, `gen_proxy_signal`, and `gen_proxy_method_call` to be clear as to what they get. The latter in particular is confusing, because the parameter names are not consistent with the names of the variables passed to it (`member_name` / `method_name` are switched) .
> New commit, or squash into the same one?

If you're going to do a general refactor like this, I'd suggest doing it in separate commit as it's unrelated to the `r#` fix. Ideally, refactors should come before other changes as it's more likely that you'd need to revert a functional change than a refactor, but I don't want to make things difficult for you, in case you're not too familiar with git rebasing etc.

---

P.S. Could you please do me a huge personal favour and not start every sentence on a new line? Thanks. :pray:  I know it's a big trend now but not everyone prefers it (I find the text hard to read) and it's grammatically incorrect anyway.

**Comment by zeenix** [comment]
> This is technically a BREAKING CHANGE,
though it seems unlikely anyone wants an r# prefix in their
dbus names or relies upon the previous behavior.

BTW, you can't have an `r#` in D-Bus member names so I don't think this is a breaking change.

File: zbus_macros/src/proxy.rs (hunk 2 above)
Comment (hepptho) [reply zbus_macros/src/proxy.rs]: No worries, I can rebase with the best of them. (It's because I screw up so much.) RE line breaks: Sure thing, though I did keep the line breaks in the commit message, because the [guidelines](https://handbook.gnome.org/development/commit-messages.html) linked in CONTRIBUTING.md have a character limit per line.

**Comment by hepptho** [comment]
Changes in the last force-push: Put a refactoring commit with name changes before the main commit.

File: zbus_macros/src/proxy.rs (hunk 2 above)
Comment (zeenix) [reply zbus_macros/src/proxy.rs]: > No worries, I can rebase with the best of them. (It's because I screw up so much.) RE line breaks: Sure thing,

:+1: 

> though I did keep the line breaks in the commit message, because the [guidelines](https://handbook.gnome.org/development/commit-messages.html) linked in CONTRIBUTING.md have a character limit per line.

That's very different. Breaking the line for the line limit on a word boundary is very normal and grammatically correct as well. Breaking the line for a new paragraph is also fine but then you need an empty line in between (which you seem to have done in the commit log, so all good).

File: zbus_macros/src/proxy.rs [hunk 3]
```diff
@@ -800,7 +804,7 @@ fn gen_proxy_signal(
     proxy_name: &Ident,
     iface_name: &str,
     signal_name: &str,
-    rust_method_name: &str,
+    r_hash_stripped_rust_method_name: &str,
```
Comment (zeenix) [inline zbus_macros/src/proxy.rs]: Don't think we need to rename this one. The `r#` being removed, isn't super important for this method.

File: zbus_macros/src/proxy.rs [hunk 4]
```diff
@@ -668,7 +672,7 @@ fn gen_proxy_method_call(
 
 fn gen_proxy_property(
     property_name: &str,
-    rust_method_name: &str,
+    r_hash_stripped_rust_method_name: &str,
```
Comment (zeenix) [inline zbus_macros/src/proxy.rs]: Same here.

**Review by zeenix — CHANGES_REQUESTED** [review]
LGTM otherwise. We're merging soon. :)

File: zbus_macros/src/proxy.rs (hunk 3 above)
Comment (hepptho) [reply zbus_macros/src/proxy.rs]: Done :)

File: zbus_macros/src/proxy.rs (hunk 4 above)
Comment (hepptho) [reply zbus_macros/src/proxy.rs]: Done :)

File: zbus_macros/src/proxy.rs [hunk 5]
```diff
@@ -209,6 +209,9 @@ pub fn create_proxy(
             let property = method_attrs.property.as_ref();
 
             let rust_method_name = m.sig.ident.to_string();
+            let r#_stripped_rust_method_name = rust_method_name
```
Comment (zeenix) [inline zbus_macros/src/proxy.rs:212]: I think we can just shadow `rust_method_name` here instead of using a new name (just like for the function arguments). So this can just be:

```rust
let rust_method_name = rust_method_name
````

File: zbus_macros/src/proxy.rs [hunk 6]
```diff
@@ -548,7 +551,8 @@ fn gen_proxy_method_call(
         _ => None,
     };
 
-    let method = Ident::new(rust_method_name, Span::call_site());
+    let mut method = parse_str::<Ident>(rust_method_name)?;
+    method.set_span(Span::call_site());
```
Comment (zeenix) [inline zbus_macros/src/proxy.rs]: Why do we need this change? :thinking:

File: zbus_macros/src/proxy.rs (hunk 5 above)
Comment (hepptho) [reply zbus_macros/src/proxy.rs:212]: That's how it was: https://github.com/z-galaxy/zbus/compare/840292f3520ca224440e8b42959403db5e3c71d7..0252e9948ecb48ea98ec2d6fc97617b398e264dd

But we need the original with r# to pass to gen_proxy_method_call, otherwise we need to add it back again there if it's a keyword.

File: zbus_macros/src/proxy.rs (hunk 6 above)
Comment (hepptho) [reply zbus_macros/src/proxy.rs]: `Ident::new` panics when it gets `r#keyword`, even though that's a valid identifier. I'm not sure why, but `parse_str` works.

File: zbus_macros/src/proxy.rs (hunk 5 above)
Comment (hepptho) [reply zbus_macros/src/proxy.rs:212]: More generally, we need both because there are two cases: We need the original when the identifier is reused as-is, like in proxy methods, because without `r#` it might not be valid there. And we need it without any `r#` when it is used as part of a derived identifier like `receive_{ident}` (in signals) or `cached_{ident}` (in properties), because there it's not valid _with_ `r#`.

File: zbus_macros/src/proxy.rs (hunk 6 above)
Comment (zeenix) [reply zbus_macros/src/proxy.rs]: > `Ident::new` panics when it gets `r#keyword`,

Hmm.. that sounds like a bug in `syn` then. It would be great to have an issue link in a comment above this: `

```rust
// FIXME: We should be using `Ident::new` here but currently we can't because of a `syn` bug:
// URL
```
Can you check if there is already one and if not, file one? :pray:

File: zbus_macros/src/proxy.rs (hunk 5 above)
Comment (zeenix) [reply zbus_macros/src/proxy.rs:212]: Right, thanks for explaining. Yeah, I guess it's better to be explicit here. :)

File: zbus_macros/src/proxy.rs (hunk 6 above)
Comment (hepptho) [reply zbus_macros/src/proxy.rs]: I found dtolnay/syn#669, and learned that [`Ident::new_raw`](https://docs.rs/proc-macro2/1.0.103/proc_macro2/struct.Ident.html#method.new_raw) exists. That one takes the passed string and prepends `r#` whether it's a keyword or not (though it also panics if you pass it a string that already starts with `r#`). But when I use it, the `r#` doesn't actually end up everywhere, only where needed. I suspect `quote!` quietly removes it when it's not necessary, but couldn't find any definitive word on that.

Using `Ident::new_raw` would work for us, with the added benefit that we wouldn't need to keep the original method name anymore. We can strip any `r#` so it's safe to use in derived identifiers, and `Ident::new_raw` can handle it when reused as-is even if we're left with a keyword. I am a bit uncertain if it's ok to pass everything through `Ident::new_raw`. It seems to work, there are no problems I can see, but I'm sure I'm not seeing everything. [Here's](https://github.com/hepptho/zbus/commit/9714f6cdb267d4c7b142e0512c74f0ea749ca820) what would change if we use `Ident::new_raw`. Should we go ahead with that?

Comment (zeenix) [reply zbus_macros/src/proxy.rs]: Thanks for looking into this in great detail. Looks like even `Ident::new_raw` can't handle all keywords so let's go with your solution.

File: zbus/tests/iface_and_proxy/client.rs [hunk 7]
```diff
@@ -65,10 +65,16 @@ pub async fn my_iface_test(conn: Connection, event: Event) -> zbus::Result<u32>
...
             .expect("Child node not exist");
     }
-    assert!(node
+    let my_iface = node
         .interfaces()
         .iter()
-        .any(|i| i.name() == "org.freedesktop.MyIface"));
+        .find(|i| i.name() == "org.freedesktop.MyIface");
+    assert!(my_iface.is_some());
+    let my_iface = my_iface.unwrap();
```
Comment (zeenix) [inline zbus/tests/iface_and_proxy/client.rs]: Great that you're being so thorough here. :+1: `unwrap` covers the assert before so it's unneccessary. In fact you can just append `.unwrap()` to the previous call chain.

**Review by zeenix — COMMENTED** [review]
Super close! Since you'll be addressing the last nit pick anyway, could you please edit the last commit log so you don't break the line before 74 chars:

```
The r# prefix required for identifiers that would otherwise be rust
keywords is no longer carried over into the dbus method / property /
signal names when used in interface or proxy methods.
```

File: zbus_macros/src/proxy.rs (hunk 6 above)
Comment (hepptho) [reply zbus_macros/src/proxy.rs]: To be clear, the restrictions regarding `self` and `super` mentioned in the docs of [`Ident::new_raw`](https://docs.rs/proc-macro2/1.0.103/proc_macro2/struct.Ident.html#method.new_raw) apply not only there. `r#self` / `r#super` are not allowed _anywhere_. Some keywords, it turns out, are more key than others, and not accepted in raw identifiers. The [reference](https://doc.rust-lang.org/reference/identifiers.html) lists them as `crate`, `self`, `super`, `Self`.

File: zbus/tests/iface_and_proxy/client.rs (hunk 7 above)
Comment (hepptho) [reply zbus/tests/iface_and_proxy/client.rs]: Done, and the commit message as well :)

File: zbus_macros/src/proxy.rs (hunk 6 above)
Comment (zeenix) [reply zbus_macros/src/proxy.rs]: Ah ok. Thanks. TIL.

**Comment by hepptho** [comment]
Thank you for your guidance :)

**Comment by zeenix** [comment]
> Thank you for your guidance :)

No, thank you for your patience. 😊
